/*
 * gVirtuS -- A GPGPU transparent virtualization component.
 *
 * Copyright (C) 2009-2011  The University of Napoli Parthenope at Naples.
 *
 * This file is part of gVirtuS.
 *
 * gVirtuS is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * gVirtuS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with gVirtuS; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Written by: Giuseppe Coviello <giuseppe.coviello@uniparthenope.it>,
 *             Department of Applied Science
 */

#include <iostream>

using namespace std;

extern "C" void fakeglDrawRangeElements(){ cerr << "*** glDrawRangeElements " << endl; }
extern "C" void fakeglCopyTexSubImage3D(){ cerr << "*** glCopyTexSubImage3D " << endl; }
extern "C" void fakeglTexImage3D(){ cerr << "*** glTexImage3D " << endl; }
extern "C" void fakeglTexSubImage3D(){ cerr << "*** glTexSubImage3D " << endl; }
extern "C" void fakeglActiveTexture(){ cerr << "*** glActiveTexture " << endl; }
extern "C" void fakeglClientActiveTexture(){ cerr << "*** glClientActiveTexture " << endl; }
extern "C" void fakeglCompressedTexImage1D(){ cerr << "*** glCompressedTexImage1D " << endl; }
extern "C" void fakeglCompressedTexImage2D(){ cerr << "*** glCompressedTexImage2D " << endl; }
extern "C" void fakeglCompressedTexImage3D(){ cerr << "*** glCompressedTexImage3D " << endl; }
extern "C" void fakeglCompressedTexSubImage1D(){ cerr << "*** glCompressedTexSubImage1D " << endl; }
extern "C" void fakeglCompressedTexSubImage2D(){ cerr << "*** glCompressedTexSubImage2D " << endl; }
extern "C" void fakeglCompressedTexSubImage3D(){ cerr << "*** glCompressedTexSubImage3D " << endl; }
extern "C" void fakeglGetCompressedTexImage(){ cerr << "*** glGetCompressedTexImage " << endl; }
extern "C" void fakeglLoadTransposeMatrixd(){ cerr << "*** glLoadTransposeMatrixd " << endl; }
extern "C" void fakeglLoadTransposeMatrixf(){ cerr << "*** glLoadTransposeMatrixf " << endl; }
extern "C" void fakeglMultTransposeMatrixd(){ cerr << "*** glMultTransposeMatrixd " << endl; }
extern "C" void fakeglMultTransposeMatrixf(){ cerr << "*** glMultTransposeMatrixf " << endl; }
extern "C" void fakeglMultiTexCoord1d(){ cerr << "*** glMultiTexCoord1d " << endl; }
extern "C" void fakeglMultiTexCoord1dv(){ cerr << "*** glMultiTexCoord1dv " << endl; }
extern "C" void fakeglMultiTexCoord1f(){ cerr << "*** glMultiTexCoord1f " << endl; }
extern "C" void fakeglMultiTexCoord1fv(){ cerr << "*** glMultiTexCoord1fv " << endl; }
extern "C" void fakeglMultiTexCoord1i(){ cerr << "*** glMultiTexCoord1i " << endl; }
extern "C" void fakeglMultiTexCoord1iv(){ cerr << "*** glMultiTexCoord1iv " << endl; }
extern "C" void fakeglMultiTexCoord1s(){ cerr << "*** glMultiTexCoord1s " << endl; }
extern "C" void fakeglMultiTexCoord1sv(){ cerr << "*** glMultiTexCoord1sv " << endl; }
extern "C" void fakeglMultiTexCoord2d(){ cerr << "*** glMultiTexCoord2d " << endl; }
extern "C" void fakeglMultiTexCoord2dv(){ cerr << "*** glMultiTexCoord2dv " << endl; }
extern "C" void fakeglMultiTexCoord2f(){ cerr << "*** glMultiTexCoord2f " << endl; }
extern "C" void fakeglMultiTexCoord2fv(){ cerr << "*** glMultiTexCoord2fv " << endl; }
extern "C" void fakeglMultiTexCoord2i(){ cerr << "*** glMultiTexCoord2i " << endl; }
extern "C" void fakeglMultiTexCoord2iv(){ cerr << "*** glMultiTexCoord2iv " << endl; }
extern "C" void fakeglMultiTexCoord2s(){ cerr << "*** glMultiTexCoord2s " << endl; }
extern "C" void fakeglMultiTexCoord2sv(){ cerr << "*** glMultiTexCoord2sv " << endl; }
extern "C" void fakeglMultiTexCoord3d(){ cerr << "*** glMultiTexCoord3d " << endl; }
extern "C" void fakeglMultiTexCoord3dv(){ cerr << "*** glMultiTexCoord3dv " << endl; }
extern "C" void fakeglMultiTexCoord3f(){ cerr << "*** glMultiTexCoord3f " << endl; }
extern "C" void fakeglMultiTexCoord3fv(){ cerr << "*** glMultiTexCoord3fv " << endl; }
extern "C" void fakeglMultiTexCoord3i(){ cerr << "*** glMultiTexCoord3i " << endl; }
extern "C" void fakeglMultiTexCoord3iv(){ cerr << "*** glMultiTexCoord3iv " << endl; }
extern "C" void fakeglMultiTexCoord3s(){ cerr << "*** glMultiTexCoord3s " << endl; }
extern "C" void fakeglMultiTexCoord3sv(){ cerr << "*** glMultiTexCoord3sv " << endl; }
extern "C" void fakeglMultiTexCoord4d(){ cerr << "*** glMultiTexCoord4d " << endl; }
extern "C" void fakeglMultiTexCoord4dv(){ cerr << "*** glMultiTexCoord4dv " << endl; }
extern "C" void fakeglMultiTexCoord4f(){ cerr << "*** glMultiTexCoord4f " << endl; }
extern "C" void fakeglMultiTexCoord4fv(){ cerr << "*** glMultiTexCoord4fv " << endl; }
extern "C" void fakeglMultiTexCoord4i(){ cerr << "*** glMultiTexCoord4i " << endl; }
extern "C" void fakeglMultiTexCoord4iv(){ cerr << "*** glMultiTexCoord4iv " << endl; }
extern "C" void fakeglMultiTexCoord4s(){ cerr << "*** glMultiTexCoord4s " << endl; }
extern "C" void fakeglMultiTexCoord4sv(){ cerr << "*** glMultiTexCoord4sv " << endl; }
extern "C" void fakeglSampleCoverage(){ cerr << "*** glSampleCoverage " << endl; }
extern "C" void fakeglBlendColor(){ cerr << "*** glBlendColor " << endl; }
extern "C" void fakeglBlendEquation(){ cerr << "*** glBlendEquation " << endl; }
extern "C" void fakeglBlendFuncSeparate(){ cerr << "*** glBlendFuncSeparate " << endl; }
extern "C" void fakeglFogCoordPointer(){ cerr << "*** glFogCoordPointer " << endl; }
extern "C" void fakeglFogCoordd(){ cerr << "*** glFogCoordd " << endl; }
extern "C" void fakeglFogCoorddv(){ cerr << "*** glFogCoorddv " << endl; }
extern "C" void fakeglFogCoordf(){ cerr << "*** glFogCoordf " << endl; }
extern "C" void fakeglFogCoordfv(){ cerr << "*** glFogCoordfv " << endl; }
extern "C" void fakeglMultiDrawArrays(){ cerr << "*** glMultiDrawArrays " << endl; }
extern "C" void fakeglMultiDrawElements(){ cerr << "*** glMultiDrawElements " << endl; }
extern "C" void fakeglPointParameterf(){ cerr << "*** glPointParameterf " << endl; }
extern "C" void fakeglPointParameterfv(){ cerr << "*** glPointParameterfv " << endl; }
extern "C" void fakeglSecondaryColor3b(){ cerr << "*** glSecondaryColor3b " << endl; }
extern "C" void fakeglSecondaryColor3bv(){ cerr << "*** glSecondaryColor3bv " << endl; }
extern "C" void fakeglSecondaryColor3d(){ cerr << "*** glSecondaryColor3d " << endl; }
extern "C" void fakeglSecondaryColor3dv(){ cerr << "*** glSecondaryColor3dv " << endl; }
extern "C" void fakeglSecondaryColor3f(){ cerr << "*** glSecondaryColor3f " << endl; }
extern "C" void fakeglSecondaryColor3fv(){ cerr << "*** glSecondaryColor3fv " << endl; }
extern "C" void fakeglSecondaryColor3i(){ cerr << "*** glSecondaryColor3i " << endl; }
extern "C" void fakeglSecondaryColor3iv(){ cerr << "*** glSecondaryColor3iv " << endl; }
extern "C" void fakeglSecondaryColor3s(){ cerr << "*** glSecondaryColor3s " << endl; }
extern "C" void fakeglSecondaryColor3sv(){ cerr << "*** glSecondaryColor3sv " << endl; }
extern "C" void fakeglSecondaryColor3ub(){ cerr << "*** glSecondaryColor3ub " << endl; }
extern "C" void fakeglSecondaryColor3ubv(){ cerr << "*** glSecondaryColor3ubv " << endl; }
extern "C" void fakeglSecondaryColor3ui(){ cerr << "*** glSecondaryColor3ui " << endl; }
extern "C" void fakeglSecondaryColor3uiv(){ cerr << "*** glSecondaryColor3uiv " << endl; }
extern "C" void fakeglSecondaryColor3us(){ cerr << "*** glSecondaryColor3us " << endl; }
extern "C" void fakeglSecondaryColor3usv(){ cerr << "*** glSecondaryColor3usv " << endl; }
extern "C" void fakeglSecondaryColorPointer(){ cerr << "*** glSecondaryColorPointer " << endl; }
extern "C" void fakeglWindowPos2d(){ cerr << "*** glWindowPos2d " << endl; }
extern "C" void fakeglWindowPos2dv(){ cerr << "*** glWindowPos2dv " << endl; }
extern "C" void fakeglWindowPos2f(){ cerr << "*** glWindowPos2f " << endl; }
extern "C" void fakeglWindowPos2fv(){ cerr << "*** glWindowPos2fv " << endl; }
extern "C" void fakeglWindowPos2i(){ cerr << "*** glWindowPos2i " << endl; }
extern "C" void fakeglWindowPos2iv(){ cerr << "*** glWindowPos2iv " << endl; }
extern "C" void fakeglWindowPos2s(){ cerr << "*** glWindowPos2s " << endl; }
extern "C" void fakeglWindowPos2sv(){ cerr << "*** glWindowPos2sv " << endl; }
extern "C" void fakeglWindowPos3d(){ cerr << "*** glWindowPos3d " << endl; }
extern "C" void fakeglWindowPos3dv(){ cerr << "*** glWindowPos3dv " << endl; }
extern "C" void fakeglWindowPos3f(){ cerr << "*** glWindowPos3f " << endl; }
extern "C" void fakeglWindowPos3fv(){ cerr << "*** glWindowPos3fv " << endl; }
extern "C" void fakeglWindowPos3i(){ cerr << "*** glWindowPos3i " << endl; }
extern "C" void fakeglWindowPos3iv(){ cerr << "*** glWindowPos3iv " << endl; }
extern "C" void fakeglWindowPos3s(){ cerr << "*** glWindowPos3s " << endl; }
extern "C" void fakeglWindowPos3sv(){ cerr << "*** glWindowPos3sv " << endl; }
extern "C" void fakeglBeginQuery(){ cerr << "*** glBeginQuery " << endl; }
extern "C" void fakeglBindBuffer(){ cerr << "*** glBindBuffer " << endl; }
extern "C" void fakeglBufferData(){ cerr << "*** glBufferData " << endl; }
extern "C" void fakeglBufferSubData(){ cerr << "*** glBufferSubData " << endl; }
extern "C" void fakeglDeleteBuffers(){ cerr << "*** glDeleteBuffers " << endl; }
extern "C" void fakeglDeleteQueries(){ cerr << "*** glDeleteQueries " << endl; }
extern "C" void fakeglEndQuery(){ cerr << "*** glEndQuery " << endl; }
extern "C" void fakeglGenQueries(){ cerr << "*** glGenQueries " << endl; }
extern "C" void fakeglGetBufferParameteriv(){ cerr << "*** glGetBufferParameteriv " << endl; }
extern "C" void fakeglGetBufferPointerv(){ cerr << "*** glGetBufferPointerv " << endl; }
extern "C" void fakeglGetBufferSubData(){ cerr << "*** glGetBufferSubData " << endl; }
extern "C" void fakeglGetQueryObjectiv(){ cerr << "*** glGetQueryObjectiv " << endl; }
extern "C" void fakeglGetQueryObjectuiv(){ cerr << "*** glGetQueryObjectuiv " << endl; }
extern "C" void fakeglGetQueryiv(){ cerr << "*** glGetQueryiv " << endl; }
extern "C" void fakeglIsBuffer(){ cerr << "*** glIsBuffer " << endl; }
extern "C" void fakeglIsQuery(){ cerr << "*** glIsQuery " << endl; }
extern "C" void fakeglMapBuffer(){ cerr << "*** glMapBuffer " << endl; }
extern "C" void fakeglUnmapBuffer(){ cerr << "*** glUnmapBuffer " << endl; }
extern "C" void fakeglAttachShader(){ cerr << "*** glAttachShader " << endl; }
extern "C" void fakeglBindAttribLocation(){ cerr << "*** glBindAttribLocation " << endl; }
extern "C" void fakeglBlendEquationSeparate(){ cerr << "*** glBlendEquationSeparate " << endl; }
extern "C" void fakeglCompileShader(){ cerr << "*** glCompileShader " << endl; }
extern "C" void fakeglCreateProgram(){ cerr << "*** glCreateProgram " << endl; }
extern "C" void fakeglCreateShader(){ cerr << "*** glCreateShader " << endl; }
extern "C" void fakeglDeleteProgram(){ cerr << "*** glDeleteProgram " << endl; }
extern "C" void fakeglDeleteShader(){ cerr << "*** glDeleteShader " << endl; }
extern "C" void fakeglDetachShader(){ cerr << "*** glDetachShader " << endl; }
extern "C" void fakeglDisableVertexAttribArray(){ cerr << "*** glDisableVertexAttribArray " << endl; }
extern "C" void fakeglDrawBuffers(){ cerr << "*** glDrawBuffers " << endl; }
extern "C" void fakeglEnableVertexAttribArray(){ cerr << "*** glEnableVertexAttribArray " << endl; }
extern "C" void fakeglGetActiveAttrib(){ cerr << "*** glGetActiveAttrib " << endl; }
extern "C" void fakeglGetActiveUniform(){ cerr << "*** glGetActiveUniform " << endl; }
extern "C" void fakeglGetAttachedShaders(){ cerr << "*** glGetAttachedShaders " << endl; }
extern "C" void fakeglGetAttribLocation(){ cerr << "*** glGetAttribLocation " << endl; }
extern "C" void fakeglGetProgramInfoLog(){ cerr << "*** glGetProgramInfoLog " << endl; }
extern "C" void fakeglGetProgramiv(){ cerr << "*** glGetProgramiv " << endl; }
extern "C" void fakeglGetShaderInfoLog(){ cerr << "*** glGetShaderInfoLog " << endl; }
extern "C" void fakeglGetShaderSource(){ cerr << "*** glGetShaderSource " << endl; }
extern "C" void fakeglGetShaderiv(){ cerr << "*** glGetShaderiv " << endl; }
extern "C" void fakeglGetUniformLocation(){ cerr << "*** glGetUniformLocation " << endl; }
extern "C" void fakeglGetUniformfv(){ cerr << "*** glGetUniformfv " << endl; }
extern "C" void fakeglGetUniformiv(){ cerr << "*** glGetUniformiv " << endl; }
extern "C" void fakeglGetVertexAttribPointerv(){ cerr << "*** glGetVertexAttribPointerv " << endl; }
extern "C" void fakeglGetVertexAttribdv(){ cerr << "*** glGetVertexAttribdv " << endl; }
extern "C" void fakeglGetVertexAttribfv(){ cerr << "*** glGetVertexAttribfv " << endl; }
extern "C" void fakeglGetVertexAttribiv(){ cerr << "*** glGetVertexAttribiv " << endl; }
extern "C" void fakeglIsProgram(){ cerr << "*** glIsProgram " << endl; }
extern "C" void fakeglIsShader(){ cerr << "*** glIsShader " << endl; }
extern "C" void fakeglLinkProgram(){ cerr << "*** glLinkProgram " << endl; }
extern "C" void fakeglShaderSource(){ cerr << "*** glShaderSource " << endl; }
extern "C" void fakeglStencilFuncSeparate(){ cerr << "*** glStencilFuncSeparate " << endl; }
extern "C" void fakeglStencilMaskSeparate(){ cerr << "*** glStencilMaskSeparate " << endl; }
extern "C" void fakeglStencilOpSeparate(){ cerr << "*** glStencilOpSeparate " << endl; }
extern "C" void fakeglUniform1f(){ cerr << "*** glUniform1f " << endl; }
extern "C" void fakeglUniform1fv(){ cerr << "*** glUniform1fv " << endl; }
extern "C" void fakeglUniform1i(){ cerr << "*** glUniform1i " << endl; }
extern "C" void fakeglUniform1iv(){ cerr << "*** glUniform1iv " << endl; }
extern "C" void fakeglUniform2f(){ cerr << "*** glUniform2f " << endl; }
extern "C" void fakeglUniform2fv(){ cerr << "*** glUniform2fv " << endl; }
extern "C" void fakeglUniform2i(){ cerr << "*** glUniform2i " << endl; }
extern "C" void fakeglUniform2iv(){ cerr << "*** glUniform2iv " << endl; }
extern "C" void fakeglUniform3f(){ cerr << "*** glUniform3f " << endl; }
extern "C" void fakeglUniform3fv(){ cerr << "*** glUniform3fv " << endl; }
extern "C" void fakeglUniform3i(){ cerr << "*** glUniform3i " << endl; }
extern "C" void fakeglUniform3iv(){ cerr << "*** glUniform3iv " << endl; }
extern "C" void fakeglUniform4f(){ cerr << "*** glUniform4f " << endl; }
extern "C" void fakeglUniform4fv(){ cerr << "*** glUniform4fv " << endl; }
extern "C" void fakeglUniform4i(){ cerr << "*** glUniform4i " << endl; }
extern "C" void fakeglUniform4iv(){ cerr << "*** glUniform4iv " << endl; }
extern "C" void fakeglUniformMatrix2fv(){ cerr << "*** glUniformMatrix2fv " << endl; }
extern "C" void fakeglUniformMatrix3fv(){ cerr << "*** glUniformMatrix3fv " << endl; }
extern "C" void fakeglUniformMatrix4fv(){ cerr << "*** glUniformMatrix4fv " << endl; }
extern "C" void fakeglUseProgram(){ cerr << "*** glUseProgram " << endl; }
extern "C" void fakeglValidateProgram(){ cerr << "*** glValidateProgram " << endl; }
extern "C" void fakeglVertexAttrib1d(){ cerr << "*** glVertexAttrib1d " << endl; }
extern "C" void fakeglVertexAttrib1dv(){ cerr << "*** glVertexAttrib1dv " << endl; }
extern "C" void fakeglVertexAttrib1f(){ cerr << "*** glVertexAttrib1f " << endl; }
extern "C" void fakeglVertexAttrib1fv(){ cerr << "*** glVertexAttrib1fv " << endl; }
extern "C" void fakeglVertexAttrib1s(){ cerr << "*** glVertexAttrib1s " << endl; }
extern "C" void fakeglVertexAttrib1sv(){ cerr << "*** glVertexAttrib1sv " << endl; }
extern "C" void fakeglVertexAttrib2d(){ cerr << "*** glVertexAttrib2d " << endl; }
extern "C" void fakeglVertexAttrib2dv(){ cerr << "*** glVertexAttrib2dv " << endl; }
extern "C" void fakeglVertexAttrib2f(){ cerr << "*** glVertexAttrib2f " << endl; }
extern "C" void fakeglVertexAttrib2fv(){ cerr << "*** glVertexAttrib2fv " << endl; }
extern "C" void fakeglVertexAttrib2s(){ cerr << "*** glVertexAttrib2s " << endl; }
extern "C" void fakeglVertexAttrib2sv(){ cerr << "*** glVertexAttrib2sv " << endl; }
extern "C" void fakeglVertexAttrib3d(){ cerr << "*** glVertexAttrib3d " << endl; }
extern "C" void fakeglVertexAttrib3dv(){ cerr << "*** glVertexAttrib3dv " << endl; }
extern "C" void fakeglVertexAttrib3f(){ cerr << "*** glVertexAttrib3f " << endl; }
extern "C" void fakeglVertexAttrib3fv(){ cerr << "*** glVertexAttrib3fv " << endl; }
extern "C" void fakeglVertexAttrib3s(){ cerr << "*** glVertexAttrib3s " << endl; }
extern "C" void fakeglVertexAttrib3sv(){ cerr << "*** glVertexAttrib3sv " << endl; }
extern "C" void fakeglVertexAttrib4Nbv(){ cerr << "*** glVertexAttrib4Nbv " << endl; }
extern "C" void fakeglVertexAttrib4Niv(){ cerr << "*** glVertexAttrib4Niv " << endl; }
extern "C" void fakeglVertexAttrib4Nsv(){ cerr << "*** glVertexAttrib4Nsv " << endl; }
extern "C" void fakeglVertexAttrib4Nub(){ cerr << "*** glVertexAttrib4Nub " << endl; }
extern "C" void fakeglVertexAttrib4Nubv(){ cerr << "*** glVertexAttrib4Nubv " << endl; }
extern "C" void fakeglVertexAttrib4Nuiv(){ cerr << "*** glVertexAttrib4Nuiv " << endl; }
extern "C" void fakeglVertexAttrib4Nusv(){ cerr << "*** glVertexAttrib4Nusv " << endl; }
extern "C" void fakeglVertexAttrib4bv(){ cerr << "*** glVertexAttrib4bv " << endl; }
extern "C" void fakeglVertexAttrib4d(){ cerr << "*** glVertexAttrib4d " << endl; }
extern "C" void fakeglVertexAttrib4dv(){ cerr << "*** glVertexAttrib4dv " << endl; }
extern "C" void fakeglVertexAttrib4f(){ cerr << "*** glVertexAttrib4f " << endl; }
extern "C" void fakeglVertexAttrib4fv(){ cerr << "*** glVertexAttrib4fv " << endl; }
extern "C" void fakeglVertexAttrib4iv(){ cerr << "*** glVertexAttrib4iv " << endl; }
extern "C" void fakeglVertexAttrib4s(){ cerr << "*** glVertexAttrib4s " << endl; }
extern "C" void fakeglVertexAttrib4sv(){ cerr << "*** glVertexAttrib4sv " << endl; }
extern "C" void fakeglVertexAttrib4ubv(){ cerr << "*** glVertexAttrib4ubv " << endl; }
extern "C" void fakeglVertexAttrib4uiv(){ cerr << "*** glVertexAttrib4uiv " << endl; }
extern "C" void fakeglVertexAttrib4usv(){ cerr << "*** glVertexAttrib4usv " << endl; }
extern "C" void fakeglVertexAttribPointer(){ cerr << "*** glVertexAttribPointer " << endl; }
extern "C" void fakeglUniformMatrix2x3fv(){ cerr << "*** glUniformMatrix2x3fv " << endl; }
extern "C" void fakeglUniformMatrix2x4fv(){ cerr << "*** glUniformMatrix2x4fv " << endl; }
extern "C" void fakeglUniformMatrix3x2fv(){ cerr << "*** glUniformMatrix3x2fv " << endl; }
extern "C" void fakeglUniformMatrix3x4fv(){ cerr << "*** glUniformMatrix3x4fv " << endl; }
extern "C" void fakeglUniformMatrix4x2fv(){ cerr << "*** glUniformMatrix4x2fv " << endl; }
extern "C" void fakeglUniformMatrix4x3fv(){ cerr << "*** glUniformMatrix4x3fv " << endl; }
extern "C" void fakeglClampColorARB(){ cerr << "*** glClampColorARB " << endl; }
extern "C" void fakeglDrawBuffersARB(){ cerr << "*** glDrawBuffersARB " << endl; }
extern "C" void fakeglColorSubTable(){ cerr << "*** glColorSubTable " << endl; }
extern "C" void fakeglColorTable(){ cerr << "*** glColorTable " << endl; }
extern "C" void fakeglColorTableParameterfv(){ cerr << "*** glColorTableParameterfv " << endl; }
extern "C" void fakeglColorTableParameteriv(){ cerr << "*** glColorTableParameteriv " << endl; }
extern "C" void fakeglConvolutionFilter1D(){ cerr << "*** glConvolutionFilter1D " << endl; }
extern "C" void fakeglConvolutionFilter2D(){ cerr << "*** glConvolutionFilter2D " << endl; }
extern "C" void fakeglConvolutionParameterf(){ cerr << "*** glConvolutionParameterf " << endl; }
extern "C" void fakeglConvolutionParameterfv(){ cerr << "*** glConvolutionParameterfv " << endl; }
extern "C" void fakeglConvolutionParameteri(){ cerr << "*** glConvolutionParameteri " << endl; }
extern "C" void fakeglConvolutionParameteriv(){ cerr << "*** glConvolutionParameteriv " << endl; }
extern "C" void fakeglCopyColorSubTable(){ cerr << "*** glCopyColorSubTable " << endl; }
extern "C" void fakeglCopyColorTable(){ cerr << "*** glCopyColorTable " << endl; }
extern "C" void fakeglCopyConvolutionFilter1D(){ cerr << "*** glCopyConvolutionFilter1D " << endl; }
extern "C" void fakeglCopyConvolutionFilter2D(){ cerr << "*** glCopyConvolutionFilter2D " << endl; }
extern "C" void fakeglGetColorTable(){ cerr << "*** glGetColorTable " << endl; }
extern "C" void fakeglGetColorTableParameterfv(){ cerr << "*** glGetColorTableParameterfv " << endl; }
extern "C" void fakeglGetColorTableParameteriv(){ cerr << "*** glGetColorTableParameteriv " << endl; }
extern "C" void fakeglGetConvolutionFilter(){ cerr << "*** glGetConvolutionFilter " << endl; }
extern "C" void fakeglGetConvolutionParameterfv(){ cerr << "*** glGetConvolutionParameterfv " << endl; }
extern "C" void fakeglGetConvolutionParameteriv(){ cerr << "*** glGetConvolutionParameteriv " << endl; }
extern "C" void fakeglGetHistogram(){ cerr << "*** glGetHistogram " << endl; }
extern "C" void fakeglGetHistogramParameterfv(){ cerr << "*** glGetHistogramParameterfv " << endl; }
extern "C" void fakeglGetHistogramParameteriv(){ cerr << "*** glGetHistogramParameteriv " << endl; }
extern "C" void fakeglGetMinmax(){ cerr << "*** glGetMinmax " << endl; }
extern "C" void fakeglGetMinmaxParameterfv(){ cerr << "*** glGetMinmaxParameterfv " << endl; }
extern "C" void fakeglGetMinmaxParameteriv(){ cerr << "*** glGetMinmaxParameteriv " << endl; }
extern "C" void fakeglGetSeparableFilter(){ cerr << "*** glGetSeparableFilter " << endl; }
extern "C" void fakeglHistogram(){ cerr << "*** glHistogram " << endl; }
extern "C" void fakeglMinmax(){ cerr << "*** glMinmax " << endl; }
extern "C" void fakeglResetHistogram(){ cerr << "*** glResetHistogram " << endl; }
extern "C" void fakeglResetMinmax(){ cerr << "*** glResetMinmax " << endl; }
extern "C" void fakeglSeparableFilter2D(){ cerr << "*** glSeparableFilter2D " << endl; }
extern "C" void fakeglSampleCoverageARB(){ cerr << "*** glSampleCoverageARB " << endl; }
extern "C" void fakeglActiveTextureARB(){ cerr << "*** glActiveTextureARB " << endl; }
extern "C" void fakeglClientActiveTextureARB(){ cerr << "*** glClientActiveTextureARB " << endl; }
extern "C" void fakeglMultiTexCoord1dARB(){ cerr << "*** glMultiTexCoord1dARB " << endl; }
extern "C" void fakeglMultiTexCoord1dvARB(){ cerr << "*** glMultiTexCoord1dvARB " << endl; }
extern "C" void fakeglMultiTexCoord1fARB(){ cerr << "*** glMultiTexCoord1fARB " << endl; }
extern "C" void fakeglMultiTexCoord1fvARB(){ cerr << "*** glMultiTexCoord1fvARB " << endl; }
extern "C" void fakeglMultiTexCoord1iARB(){ cerr << "*** glMultiTexCoord1iARB " << endl; }
extern "C" void fakeglMultiTexCoord1ivARB(){ cerr << "*** glMultiTexCoord1ivARB " << endl; }
extern "C" void fakeglMultiTexCoord1sARB(){ cerr << "*** glMultiTexCoord1sARB " << endl; }
extern "C" void fakeglMultiTexCoord1svARB(){ cerr << "*** glMultiTexCoord1svARB " << endl; }
extern "C" void fakeglMultiTexCoord2dARB(){ cerr << "*** glMultiTexCoord2dARB " << endl; }
extern "C" void fakeglMultiTexCoord2dvARB(){ cerr << "*** glMultiTexCoord2dvARB " << endl; }
extern "C" void fakeglMultiTexCoord2fARB(){ cerr << "*** glMultiTexCoord2fARB " << endl; }
extern "C" void fakeglMultiTexCoord2fvARB(){ cerr << "*** glMultiTexCoord2fvARB " << endl; }
extern "C" void fakeglMultiTexCoord2iARB(){ cerr << "*** glMultiTexCoord2iARB " << endl; }
extern "C" void fakeglMultiTexCoord2ivARB(){ cerr << "*** glMultiTexCoord2ivARB " << endl; }
extern "C" void fakeglMultiTexCoord2sARB(){ cerr << "*** glMultiTexCoord2sARB " << endl; }
extern "C" void fakeglMultiTexCoord2svARB(){ cerr << "*** glMultiTexCoord2svARB " << endl; }
extern "C" void fakeglMultiTexCoord3dARB(){ cerr << "*** glMultiTexCoord3dARB " << endl; }
extern "C" void fakeglMultiTexCoord3dvARB(){ cerr << "*** glMultiTexCoord3dvARB " << endl; }
extern "C" void fakeglMultiTexCoord3fARB(){ cerr << "*** glMultiTexCoord3fARB " << endl; }
extern "C" void fakeglMultiTexCoord3fvARB(){ cerr << "*** glMultiTexCoord3fvARB " << endl; }
extern "C" void fakeglMultiTexCoord3iARB(){ cerr << "*** glMultiTexCoord3iARB " << endl; }
extern "C" void fakeglMultiTexCoord3ivARB(){ cerr << "*** glMultiTexCoord3ivARB " << endl; }
extern "C" void fakeglMultiTexCoord3sARB(){ cerr << "*** glMultiTexCoord3sARB " << endl; }
extern "C" void fakeglMultiTexCoord3svARB(){ cerr << "*** glMultiTexCoord3svARB " << endl; }
extern "C" void fakeglMultiTexCoord4dARB(){ cerr << "*** glMultiTexCoord4dARB " << endl; }
extern "C" void fakeglMultiTexCoord4dvARB(){ cerr << "*** glMultiTexCoord4dvARB " << endl; }
extern "C" void fakeglMultiTexCoord4fARB(){ cerr << "*** glMultiTexCoord4fARB " << endl; }
extern "C" void fakeglMultiTexCoord4fvARB(){ cerr << "*** glMultiTexCoord4fvARB " << endl; }
extern "C" void fakeglMultiTexCoord4iARB(){ cerr << "*** glMultiTexCoord4iARB " << endl; }
extern "C" void fakeglMultiTexCoord4ivARB(){ cerr << "*** glMultiTexCoord4ivARB " << endl; }
extern "C" void fakeglMultiTexCoord4sARB(){ cerr << "*** glMultiTexCoord4sARB " << endl; }
extern "C" void fakeglMultiTexCoord4svARB(){ cerr << "*** glMultiTexCoord4svARB " << endl; }
extern "C" void fakeglBeginQueryARB(){ cerr << "*** glBeginQueryARB " << endl; }
extern "C" void fakeglDeleteQueriesARB(){ cerr << "*** glDeleteQueriesARB " << endl; }
extern "C" void fakeglEndQueryARB(){ cerr << "*** glEndQueryARB " << endl; }
extern "C" void fakeglGenQueriesARB(){ cerr << "*** glGenQueriesARB " << endl; }
extern "C" void fakeglGetQueryObjectivARB(){ cerr << "*** glGetQueryObjectivARB " << endl; }
extern "C" void fakeglGetQueryObjectuivARB(){ cerr << "*** glGetQueryObjectuivARB " << endl; }
extern "C" void fakeglGetQueryivARB(){ cerr << "*** glGetQueryivARB " << endl; }
extern "C" void fakeglIsQueryARB(){ cerr << "*** glIsQueryARB " << endl; }
extern "C" void fakeglPointParameterfARB(){ cerr << "*** glPointParameterfARB " << endl; }
extern "C" void fakeglPointParameterfvARB(){ cerr << "*** glPointParameterfvARB " << endl; }
extern "C" void fakeglAttachObjectARB(){ cerr << "*** glAttachObjectARB " << endl; }
extern "C" void fakeglCompileShaderARB(){ cerr << "*** glCompileShaderARB " << endl; }
extern "C" void fakeglCreateProgramObjectARB(){ cerr << "*** glCreateProgramObjectARB " << endl; }
extern "C" void fakeglCreateShaderObjectARB(){ cerr << "*** glCreateShaderObjectARB " << endl; }
extern "C" void fakeglDeleteObjectARB(){ cerr << "*** glDeleteObjectARB " << endl; }
extern "C" void fakeglDetachObjectARB(){ cerr << "*** glDetachObjectARB " << endl; }
extern "C" void fakeglGetActiveUniformARB(){ cerr << "*** glGetActiveUniformARB " << endl; }
extern "C" void fakeglGetAttachedObjectsARB(){ cerr << "*** glGetAttachedObjectsARB " << endl; }
extern "C" void fakeglGetHandleARB(){ cerr << "*** glGetHandleARB " << endl; }
extern "C" void fakeglGetInfoLogARB(){ cerr << "*** glGetInfoLogARB " << endl; }
extern "C" void fakeglGetObjectParameterfvARB(){ cerr << "*** glGetObjectParameterfvARB " << endl; }
extern "C" void fakeglGetObjectParameterivARB(){ cerr << "*** glGetObjectParameterivARB " << endl; }
extern "C" void fakeglGetShaderSourceARB(){ cerr << "*** glGetShaderSourceARB " << endl; }
extern "C" void fakeglGetUniformLocationARB(){ cerr << "*** glGetUniformLocationARB " << endl; }
extern "C" void fakeglGetUniformfvARB(){ cerr << "*** glGetUniformfvARB " << endl; }
extern "C" void fakeglGetUniformivARB(){ cerr << "*** glGetUniformivARB " << endl; }
extern "C" void fakeglLinkProgramARB(){ cerr << "*** glLinkProgramARB " << endl; }
extern "C" void fakeglShaderSourceARB(){ cerr << "*** glShaderSourceARB " << endl; }
extern "C" void fakeglUniform1fARB(){ cerr << "*** glUniform1fARB " << endl; }
extern "C" void fakeglUniform1fvARB(){ cerr << "*** glUniform1fvARB " << endl; }
extern "C" void fakeglUniform1iARB(){ cerr << "*** glUniform1iARB " << endl; }
extern "C" void fakeglUniform1ivARB(){ cerr << "*** glUniform1ivARB " << endl; }
extern "C" void fakeglUniform2fARB(){ cerr << "*** glUniform2fARB " << endl; }
extern "C" void fakeglUniform2fvARB(){ cerr << "*** glUniform2fvARB " << endl; }
extern "C" void fakeglUniform2iARB(){ cerr << "*** glUniform2iARB " << endl; }
extern "C" void fakeglUniform2ivARB(){ cerr << "*** glUniform2ivARB " << endl; }
extern "C" void fakeglUniform3fARB(){ cerr << "*** glUniform3fARB " << endl; }
extern "C" void fakeglUniform3fvARB(){ cerr << "*** glUniform3fvARB " << endl; }
extern "C" void fakeglUniform3iARB(){ cerr << "*** glUniform3iARB " << endl; }
extern "C" void fakeglUniform3ivARB(){ cerr << "*** glUniform3ivARB " << endl; }
extern "C" void fakeglUniform4fARB(){ cerr << "*** glUniform4fARB " << endl; }
extern "C" void fakeglUniform4fvARB(){ cerr << "*** glUniform4fvARB " << endl; }
extern "C" void fakeglUniform4iARB(){ cerr << "*** glUniform4iARB " << endl; }
extern "C" void fakeglUniform4ivARB(){ cerr << "*** glUniform4ivARB " << endl; }
extern "C" void fakeglUniformMatrix2fvARB(){ cerr << "*** glUniformMatrix2fvARB " << endl; }
extern "C" void fakeglUniformMatrix3fvARB(){ cerr << "*** glUniformMatrix3fvARB " << endl; }
extern "C" void fakeglUniformMatrix4fvARB(){ cerr << "*** glUniformMatrix4fvARB " << endl; }
extern "C" void fakeglUseProgramObjectARB(){ cerr << "*** glUseProgramObjectARB " << endl; }
extern "C" void fakeglValidateProgramARB(){ cerr << "*** glValidateProgramARB " << endl; }
extern "C" void fakeglCompressedTexImage1DARB(){ cerr << "*** glCompressedTexImage1DARB " << endl; }
extern "C" void fakeglCompressedTexImage2DARB(){ cerr << "*** glCompressedTexImage2DARB " << endl; }
extern "C" void fakeglCompressedTexImage3DARB(){ cerr << "*** glCompressedTexImage3DARB " << endl; }
extern "C" void fakeglCompressedTexSubImage1DARB(){ cerr << "*** glCompressedTexSubImage1DARB " << endl; }
extern "C" void fakeglCompressedTexSubImage2DARB(){ cerr << "*** glCompressedTexSubImage2DARB " << endl; }
extern "C" void fakeglCompressedTexSubImage3DARB(){ cerr << "*** glCompressedTexSubImage3DARB " << endl; }
extern "C" void fakeglGetCompressedTexImageARB(){ cerr << "*** glGetCompressedTexImageARB " << endl; }
extern "C" void fakeglLoadTransposeMatrixdARB(){ cerr << "*** glLoadTransposeMatrixdARB " << endl; }
extern "C" void fakeglLoadTransposeMatrixfARB(){ cerr << "*** glLoadTransposeMatrixfARB " << endl; }
extern "C" void fakeglMultTransposeMatrixdARB(){ cerr << "*** glMultTransposeMatrixdARB " << endl; }
extern "C" void fakeglMultTransposeMatrixfARB(){ cerr << "*** glMultTransposeMatrixfARB " << endl; }
extern "C" void fakeglBindBufferARB(){ cerr << "*** glBindBufferARB " << endl; }
extern "C" void fakeglBufferDataARB(){ cerr << "*** glBufferDataARB " << endl; }
extern "C" void fakeglBufferSubDataARB(){ cerr << "*** glBufferSubDataARB " << endl; }
extern "C" void fakeglDeleteBuffersARB(){ cerr << "*** glDeleteBuffersARB " << endl; }
extern "C" void fakeglGenBuffersARB(){ cerr << "*** glGenBuffersARB " << endl; }
extern "C" void fakeglGetBufferParameterivARB(){ cerr << "*** glGetBufferParameterivARB " << endl; }
extern "C" void fakeglGetBufferPointervARB(){ cerr << "*** glGetBufferPointervARB " << endl; }
extern "C" void fakeglGetBufferSubDataARB(){ cerr << "*** glGetBufferSubDataARB " << endl; }
extern "C" void fakeglIsBufferARB(){ cerr << "*** glIsBufferARB " << endl; }
extern "C" void fakeglMapBufferARB(){ cerr << "*** glMapBufferARB " << endl; }
extern "C" void fakeglUnmapBufferARB(){ cerr << "*** glUnmapBufferARB " << endl; }
extern "C" void fakeglBindProgramARB(){ cerr << "*** glBindProgramARB " << endl; }
extern "C" void fakeglDeleteProgramsARB(){ cerr << "*** glDeleteProgramsARB " << endl; }
extern "C" void fakeglDisableVertexAttribArrayARB(){ cerr << "*** glDisableVertexAttribArrayARB " << endl; }
extern "C" void fakeglEnableVertexAttribArrayARB(){ cerr << "*** glEnableVertexAttribArrayARB " << endl; }
extern "C" void fakeglGenProgramsARB(){ cerr << "*** glGenProgramsARB " << endl; }
extern "C" void fakeglGetProgramEnvParameterdvARB(){ cerr << "*** glGetProgramEnvParameterdvARB " << endl; }
extern "C" void fakeglGetProgramEnvParameterfvARB(){ cerr << "*** glGetProgramEnvParameterfvARB " << endl; }
extern "C" void fakeglGetProgramLocalParameterdvARB(){ cerr << "*** glGetProgramLocalParameterdvARB " << endl; }
extern "C" void fakeglGetProgramLocalParameterfvARB(){ cerr << "*** glGetProgramLocalParameterfvARB " << endl; }
extern "C" void fakeglGetProgramStringARB(){ cerr << "*** glGetProgramStringARB " << endl; }
extern "C" void fakeglGetProgramivARB(){ cerr << "*** glGetProgramivARB " << endl; }
extern "C" void fakeglGetVertexAttribPointervARB(){ cerr << "*** glGetVertexAttribPointervARB " << endl; }
extern "C" void fakeglGetVertexAttribdvARB(){ cerr << "*** glGetVertexAttribdvARB " << endl; }
extern "C" void fakeglGetVertexAttribfvARB(){ cerr << "*** glGetVertexAttribfvARB " << endl; }
extern "C" void fakeglGetVertexAttribivARB(){ cerr << "*** glGetVertexAttribivARB " << endl; }
extern "C" void fakeglIsProgramARB(){ cerr << "*** glIsProgramARB " << endl; }
extern "C" void fakeglProgramEnvParameter4dARB(){ cerr << "*** glProgramEnvParameter4dARB " << endl; }
extern "C" void fakeglProgramEnvParameter4dvARB(){ cerr << "*** glProgramEnvParameter4dvARB " << endl; }
extern "C" void fakeglProgramEnvParameter4fARB(){ cerr << "*** glProgramEnvParameter4fARB " << endl; }
extern "C" void fakeglProgramEnvParameter4fvARB(){ cerr << "*** glProgramEnvParameter4fvARB " << endl; }
extern "C" void fakeglProgramLocalParameter4dARB(){ cerr << "*** glProgramLocalParameter4dARB " << endl; }
extern "C" void fakeglProgramLocalParameter4dvARB(){ cerr << "*** glProgramLocalParameter4dvARB " << endl; }
extern "C" void fakeglProgramLocalParameter4fARB(){ cerr << "*** glProgramLocalParameter4fARB " << endl; }
extern "C" void fakeglProgramLocalParameter4fvARB(){ cerr << "*** glProgramLocalParameter4fvARB " << endl; }
extern "C" void fakeglProgramStringARB(){ cerr << "*** glProgramStringARB " << endl; }
extern "C" void fakeglVertexAttrib1dARB(){ cerr << "*** glVertexAttrib1dARB " << endl; }
extern "C" void fakeglVertexAttrib1dvARB(){ cerr << "*** glVertexAttrib1dvARB " << endl; }
extern "C" void fakeglVertexAttrib1fARB(){ cerr << "*** glVertexAttrib1fARB " << endl; }
extern "C" void fakeglVertexAttrib1fvARB(){ cerr << "*** glVertexAttrib1fvARB " << endl; }
extern "C" void fakeglVertexAttrib1sARB(){ cerr << "*** glVertexAttrib1sARB " << endl; }
extern "C" void fakeglVertexAttrib1svARB(){ cerr << "*** glVertexAttrib1svARB " << endl; }
extern "C" void fakeglVertexAttrib2dARB(){ cerr << "*** glVertexAttrib2dARB " << endl; }
extern "C" void fakeglVertexAttrib2dvARB(){ cerr << "*** glVertexAttrib2dvARB " << endl; }
extern "C" void fakeglVertexAttrib2fARB(){ cerr << "*** glVertexAttrib2fARB " << endl; }
extern "C" void fakeglVertexAttrib2fvARB(){ cerr << "*** glVertexAttrib2fvARB " << endl; }
extern "C" void fakeglVertexAttrib2sARB(){ cerr << "*** glVertexAttrib2sARB " << endl; }
extern "C" void fakeglVertexAttrib2svARB(){ cerr << "*** glVertexAttrib2svARB " << endl; }
extern "C" void fakeglVertexAttrib3dARB(){ cerr << "*** glVertexAttrib3dARB " << endl; }
extern "C" void fakeglVertexAttrib3dvARB(){ cerr << "*** glVertexAttrib3dvARB " << endl; }
extern "C" void fakeglVertexAttrib3fARB(){ cerr << "*** glVertexAttrib3fARB " << endl; }
extern "C" void fakeglVertexAttrib3fvARB(){ cerr << "*** glVertexAttrib3fvARB " << endl; }
extern "C" void fakeglVertexAttrib3sARB(){ cerr << "*** glVertexAttrib3sARB " << endl; }
extern "C" void fakeglVertexAttrib3svARB(){ cerr << "*** glVertexAttrib3svARB " << endl; }
extern "C" void fakeglVertexAttrib4NbvARB(){ cerr << "*** glVertexAttrib4NbvARB " << endl; }
extern "C" void fakeglVertexAttrib4NivARB(){ cerr << "*** glVertexAttrib4NivARB " << endl; }
extern "C" void fakeglVertexAttrib4NsvARB(){ cerr << "*** glVertexAttrib4NsvARB " << endl; }
extern "C" void fakeglVertexAttrib4NubARB(){ cerr << "*** glVertexAttrib4NubARB " << endl; }
extern "C" void fakeglVertexAttrib4NubvARB(){ cerr << "*** glVertexAttrib4NubvARB " << endl; }
extern "C" void fakeglVertexAttrib4NuivARB(){ cerr << "*** glVertexAttrib4NuivARB " << endl; }
extern "C" void fakeglVertexAttrib4NusvARB(){ cerr << "*** glVertexAttrib4NusvARB " << endl; }
extern "C" void fakeglVertexAttrib4bvARB(){ cerr << "*** glVertexAttrib4bvARB " << endl; }
extern "C" void fakeglVertexAttrib4dARB(){ cerr << "*** glVertexAttrib4dARB " << endl; }
extern "C" void fakeglVertexAttrib4dvARB(){ cerr << "*** glVertexAttrib4dvARB " << endl; }
extern "C" void fakeglVertexAttrib4fARB(){ cerr << "*** glVertexAttrib4fARB " << endl; }
extern "C" void fakeglVertexAttrib4fvARB(){ cerr << "*** glVertexAttrib4fvARB " << endl; }
extern "C" void fakeglVertexAttrib4ivARB(){ cerr << "*** glVertexAttrib4ivARB " << endl; }
extern "C" void fakeglVertexAttrib4sARB(){ cerr << "*** glVertexAttrib4sARB " << endl; }
extern "C" void fakeglVertexAttrib4svARB(){ cerr << "*** glVertexAttrib4svARB " << endl; }
extern "C" void fakeglVertexAttrib4ubvARB(){ cerr << "*** glVertexAttrib4ubvARB " << endl; }
extern "C" void fakeglVertexAttrib4uivARB(){ cerr << "*** glVertexAttrib4uivARB " << endl; }
extern "C" void fakeglVertexAttrib4usvARB(){ cerr << "*** glVertexAttrib4usvARB " << endl; }
extern "C" void fakeglVertexAttribPointerARB(){ cerr << "*** glVertexAttribPointerARB " << endl; }
extern "C" void fakeglBindAttribLocationARB(){ cerr << "*** glBindAttribLocationARB " << endl; }
extern "C" void fakeglGetActiveAttribARB(){ cerr << "*** glGetActiveAttribARB " << endl; }
extern "C" void fakeglGetAttribLocationARB(){ cerr << "*** glGetAttribLocationARB " << endl; }
extern "C" void fakeglWindowPos2dARB(){ cerr << "*** glWindowPos2dARB " << endl; }
extern "C" void fakeglWindowPos2dvARB(){ cerr << "*** glWindowPos2dvARB " << endl; }
extern "C" void fakeglWindowPos2fARB(){ cerr << "*** glWindowPos2fARB " << endl; }
extern "C" void fakeglWindowPos2fvARB(){ cerr << "*** glWindowPos2fvARB " << endl; }
extern "C" void fakeglWindowPos2iARB(){ cerr << "*** glWindowPos2iARB " << endl; }
extern "C" void fakeglWindowPos2ivARB(){ cerr << "*** glWindowPos2ivARB " << endl; }
extern "C" void fakeglWindowPos2sARB(){ cerr << "*** glWindowPos2sARB " << endl; }
extern "C" void fakeglWindowPos2svARB(){ cerr << "*** glWindowPos2svARB " << endl; }
extern "C" void fakeglWindowPos3dARB(){ cerr << "*** glWindowPos3dARB " << endl; }
extern "C" void fakeglWindowPos3dvARB(){ cerr << "*** glWindowPos3dvARB " << endl; }
extern "C" void fakeglWindowPos3fARB(){ cerr << "*** glWindowPos3fARB " << endl; }
extern "C" void fakeglWindowPos3fvARB(){ cerr << "*** glWindowPos3fvARB " << endl; }
extern "C" void fakeglWindowPos3iARB(){ cerr << "*** glWindowPos3iARB " << endl; }
extern "C" void fakeglWindowPos3ivARB(){ cerr << "*** glWindowPos3ivARB " << endl; }
extern "C" void fakeglWindowPos3sARB(){ cerr << "*** glWindowPos3sARB " << endl; }
extern "C" void fakeglWindowPos3svARB(){ cerr << "*** glWindowPos3svARB " << endl; }
extern "C" void fakeglDrawBuffersATI(){ cerr << "*** glDrawBuffersATI " << endl; }
extern "C" void fakeglGetUniformBufferSizeEXT(){ cerr << "*** glGetUniformBufferSizeEXT " << endl; }
extern "C" void fakeglGetUniformOffsetEXT(){ cerr << "*** glGetUniformOffsetEXT " << endl; }
extern "C" void fakeglUniformBufferEXT(){ cerr << "*** glUniformBufferEXT " << endl; }
extern "C" void fakeglBlendColorEXT(){ cerr << "*** glBlendColorEXT " << endl; }
extern "C" void fakeglBlendEquationSeparateEXT(){ cerr << "*** glBlendEquationSeparateEXT " << endl; }
extern "C" void fakeglBlendFuncSeparateEXT(){ cerr << "*** glBlendFuncSeparateEXT " << endl; }
extern "C" void fakeglBlendEquationEXT(){ cerr << "*** glBlendEquationEXT " << endl; }
extern "C" void fakeglLockArraysEXT(){ cerr << "*** glLockArraysEXT " << endl; }
extern "C" void fakeglUnlockArraysEXT(){ cerr << "*** glUnlockArraysEXT " << endl; }
extern "C" void fakeglDepthBoundsEXT(){ cerr << "*** glDepthBoundsEXT " << endl; }
extern "C" void fakeglColorMaskIndexedEXT(){ cerr << "*** glColorMaskIndexedEXT " << endl; }
extern "C" void fakeglDisableIndexedEXT(){ cerr << "*** glDisableIndexedEXT " << endl; }
extern "C" void fakeglEnableIndexedEXT(){ cerr << "*** glEnableIndexedEXT " << endl; }
extern "C" void fakeglGetBooleanIndexedvEXT(){ cerr << "*** glGetBooleanIndexedvEXT " << endl; }
extern "C" void fakeglGetIntegerIndexedvEXT(){ cerr << "*** glGetIntegerIndexedvEXT " << endl; }
extern "C" void fakeglIsEnabledIndexedEXT(){ cerr << "*** glIsEnabledIndexedEXT " << endl; }
extern "C" void fakeglDrawArraysInstancedEXT(){ cerr << "*** glDrawArraysInstancedEXT " << endl; }
extern "C" void fakeglDrawElementsInstancedEXT(){ cerr << "*** glDrawElementsInstancedEXT " << endl; }
extern "C" void fakeglDrawRangeElementsEXT(){ cerr << "*** glDrawRangeElementsEXT " << endl; }
extern "C" void fakeglFogCoordPointerEXT(){ cerr << "*** glFogCoordPointerEXT " << endl; }
extern "C" void fakeglFogCoorddEXT(){ cerr << "*** glFogCoorddEXT " << endl; }
extern "C" void fakeglFogCoorddvEXT(){ cerr << "*** glFogCoorddvEXT " << endl; }
extern "C" void fakeglFogCoordfEXT(){ cerr << "*** glFogCoordfEXT " << endl; }
extern "C" void fakeglFogCoordfvEXT(){ cerr << "*** glFogCoordfvEXT " << endl; }
extern "C" void fakeglBlitFramebufferEXT(){ cerr << "*** glBlitFramebufferEXT " << endl; }
extern "C" void fakeglRenderbufferStorageMultisampleEXT(){ cerr << "*** glRenderbufferStorageMultisampleEXT " << endl; }
extern "C" void fakeglBindFramebufferEXT(){ cerr << "*** glBindFramebufferEXT " << endl; }
extern "C" void fakeglBindRenderbufferEXT(){ cerr << "*** glBindRenderbufferEXT " << endl; }
extern "C" void fakeglCheckFramebufferStatusEXT(){ cerr << "*** glCheckFramebufferStatusEXT " << endl; }
extern "C" void fakeglDeleteFramebuffersEXT(){ cerr << "*** glDeleteFramebuffersEXT " << endl; }
extern "C" void fakeglDeleteRenderbuffersEXT(){ cerr << "*** glDeleteRenderbuffersEXT " << endl; }
extern "C" void fakeglFramebufferRenderbufferEXT(){ cerr << "*** glFramebufferRenderbufferEXT " << endl; }
extern "C" void fakeglFramebufferTexture1DEXT(){ cerr << "*** glFramebufferTexture1DEXT " << endl; }
extern "C" void fakeglFramebufferTexture2DEXT(){ cerr << "*** glFramebufferTexture2DEXT " << endl; }
extern "C" void fakeglFramebufferTexture3DEXT(){ cerr << "*** glFramebufferTexture3DEXT " << endl; }
extern "C" void fakeglGenFramebuffersEXT(){ cerr << "*** glGenFramebuffersEXT " << endl; }
extern "C" void fakeglGenRenderbuffersEXT(){ cerr << "*** glGenRenderbuffersEXT " << endl; }
extern "C" void fakeglGenerateMipmapEXT(){ cerr << "*** glGenerateMipmapEXT " << endl; }
extern "C" void fakeglGetFramebufferAttachmentParameterivEXT(){ cerr << "*** glGetFramebufferAttachmentParameterivEXT " << endl; }
extern "C" void fakeglGetRenderbufferParameterivEXT(){ cerr << "*** glGetRenderbufferParameterivEXT " << endl; }
extern "C" void fakeglIsFramebufferEXT(){ cerr << "*** glIsFramebufferEXT " << endl; }
extern "C" void fakeglIsRenderbufferEXT(){ cerr << "*** glIsRenderbufferEXT " << endl; }
extern "C" void fakeglRenderbufferStorageEXT(){ cerr << "*** glRenderbufferStorageEXT " << endl; }
extern "C" void fakeglFramebufferTextureEXT(){ cerr << "*** glFramebufferTextureEXT " << endl; }
extern "C" void fakeglFramebufferTextureFaceEXT(){ cerr << "*** glFramebufferTextureFaceEXT " << endl; }
extern "C" void fakeglFramebufferTextureLayerEXT(){ cerr << "*** glFramebufferTextureLayerEXT " << endl; }
extern "C" void fakeglProgramParameteriEXT(){ cerr << "*** glProgramParameteriEXT " << endl; }
extern "C" void fakeglProgramEnvParameters4fvEXT(){ cerr << "*** glProgramEnvParameters4fvEXT " << endl; }
extern "C" void fakeglProgramLocalParameters4fvEXT(){ cerr << "*** glProgramLocalParameters4fvEXT " << endl; }
extern "C" void fakeglBindFragDataLocationEXT(){ cerr << "*** glBindFragDataLocationEXT " << endl; }
extern "C" void fakeglGetFragDataLocationEXT(){ cerr << "*** glGetFragDataLocationEXT " << endl; }
extern "C" void fakeglGetUniformuivEXT(){ cerr << "*** glGetUniformuivEXT " << endl; }
extern "C" void fakeglGetVertexAttribIivEXT(){ cerr << "*** glGetVertexAttribIivEXT " << endl; }
extern "C" void fakeglGetVertexAttribIuivEXT(){ cerr << "*** glGetVertexAttribIuivEXT " << endl; }
extern "C" void fakeglUniform1uiEXT(){ cerr << "*** glUniform1uiEXT " << endl; }
extern "C" void fakeglUniform1uivEXT(){ cerr << "*** glUniform1uivEXT " << endl; }
extern "C" void fakeglUniform2uiEXT(){ cerr << "*** glUniform2uiEXT " << endl; }
extern "C" void fakeglUniform2uivEXT(){ cerr << "*** glUniform2uivEXT " << endl; }
extern "C" void fakeglUniform3uiEXT(){ cerr << "*** glUniform3uiEXT " << endl; }
extern "C" void fakeglUniform3uivEXT(){ cerr << "*** glUniform3uivEXT " << endl; }
extern "C" void fakeglUniform4uiEXT(){ cerr << "*** glUniform4uiEXT " << endl; }
extern "C" void fakeglUniform4uivEXT(){ cerr << "*** glUniform4uivEXT " << endl; }
extern "C" void fakeglVertexAttribI1iEXT(){ cerr << "*** glVertexAttribI1iEXT " << endl; }
extern "C" void fakeglVertexAttribI1ivEXT(){ cerr << "*** glVertexAttribI1ivEXT " << endl; }
extern "C" void fakeglVertexAttribI1uiEXT(){ cerr << "*** glVertexAttribI1uiEXT " << endl; }
extern "C" void fakeglVertexAttribI1uivEXT(){ cerr << "*** glVertexAttribI1uivEXT " << endl; }
extern "C" void fakeglVertexAttribI2iEXT(){ cerr << "*** glVertexAttribI2iEXT " << endl; }
extern "C" void fakeglVertexAttribI2ivEXT(){ cerr << "*** glVertexAttribI2ivEXT " << endl; }
extern "C" void fakeglVertexAttribI2uiEXT(){ cerr << "*** glVertexAttribI2uiEXT " << endl; }
extern "C" void fakeglVertexAttribI2uivEXT(){ cerr << "*** glVertexAttribI2uivEXT " << endl; }
extern "C" void fakeglVertexAttribI3iEXT(){ cerr << "*** glVertexAttribI3iEXT " << endl; }
extern "C" void fakeglVertexAttribI3ivEXT(){ cerr << "*** glVertexAttribI3ivEXT " << endl; }
extern "C" void fakeglVertexAttribI3uiEXT(){ cerr << "*** glVertexAttribI3uiEXT " << endl; }
extern "C" void fakeglVertexAttribI3uivEXT(){ cerr << "*** glVertexAttribI3uivEXT " << endl; }
extern "C" void fakeglVertexAttribI4bvEXT(){ cerr << "*** glVertexAttribI4bvEXT " << endl; }
extern "C" void fakeglVertexAttribI4iEXT(){ cerr << "*** glVertexAttribI4iEXT " << endl; }
extern "C" void fakeglVertexAttribI4ivEXT(){ cerr << "*** glVertexAttribI4ivEXT " << endl; }
extern "C" void fakeglVertexAttribI4svEXT(){ cerr << "*** glVertexAttribI4svEXT " << endl; }
extern "C" void fakeglVertexAttribI4ubvEXT(){ cerr << "*** glVertexAttribI4ubvEXT " << endl; }
extern "C" void fakeglVertexAttribI4uiEXT(){ cerr << "*** glVertexAttribI4uiEXT " << endl; }
extern "C" void fakeglVertexAttribI4uivEXT(){ cerr << "*** glVertexAttribI4uivEXT " << endl; }
extern "C" void fakeglVertexAttribI4usvEXT(){ cerr << "*** glVertexAttribI4usvEXT " << endl; }
extern "C" void fakeglVertexAttribIPointerEXT(){ cerr << "*** glVertexAttribIPointerEXT " << endl; }
extern "C" void fakeglMultiDrawArraysEXT(){ cerr << "*** glMultiDrawArraysEXT " << endl; }
extern "C" void fakeglMultiDrawElementsEXT(){ cerr << "*** glMultiDrawElementsEXT " << endl; }
extern "C" void fakeglPointParameterfEXT(){ cerr << "*** glPointParameterfEXT " << endl; }
extern "C" void fakeglPointParameterfvEXT(){ cerr << "*** glPointParameterfvEXT " << endl; }
extern "C" void fakeglSecondaryColor3bEXT(){ cerr << "*** glSecondaryColor3bEXT " << endl; }
extern "C" void fakeglSecondaryColor3bvEXT(){ cerr << "*** glSecondaryColor3bvEXT " << endl; }
extern "C" void fakeglSecondaryColor3dEXT(){ cerr << "*** glSecondaryColor3dEXT " << endl; }
extern "C" void fakeglSecondaryColor3dvEXT(){ cerr << "*** glSecondaryColor3dvEXT " << endl; }
extern "C" void fakeglSecondaryColor3fEXT(){ cerr << "*** glSecondaryColor3fEXT " << endl; }
extern "C" void fakeglSecondaryColor3fvEXT(){ cerr << "*** glSecondaryColor3fvEXT " << endl; }
extern "C" void fakeglSecondaryColor3iEXT(){ cerr << "*** glSecondaryColor3iEXT " << endl; }
extern "C" void fakeglSecondaryColor3ivEXT(){ cerr << "*** glSecondaryColor3ivEXT " << endl; }
extern "C" void fakeglSecondaryColor3sEXT(){ cerr << "*** glSecondaryColor3sEXT " << endl; }
extern "C" void fakeglSecondaryColor3svEXT(){ cerr << "*** glSecondaryColor3svEXT " << endl; }
extern "C" void fakeglSecondaryColor3ubEXT(){ cerr << "*** glSecondaryColor3ubEXT " << endl; }
extern "C" void fakeglSecondaryColor3ubvEXT(){ cerr << "*** glSecondaryColor3ubvEXT " << endl; }
extern "C" void fakeglSecondaryColor3uiEXT(){ cerr << "*** glSecondaryColor3uiEXT " << endl; }
extern "C" void fakeglSecondaryColor3uivEXT(){ cerr << "*** glSecondaryColor3uivEXT " << endl; }
extern "C" void fakeglSecondaryColor3usEXT(){ cerr << "*** glSecondaryColor3usEXT " << endl; }
extern "C" void fakeglSecondaryColor3usvEXT(){ cerr << "*** glSecondaryColor3usvEXT " << endl; }
extern "C" void fakeglSecondaryColorPointerEXT(){ cerr << "*** glSecondaryColorPointerEXT " << endl; }
extern "C" void fakeglActiveStencilFaceEXT(){ cerr << "*** glActiveStencilFaceEXT " << endl; }
extern "C" void fakeglTexImage3DEXT(){ cerr << "*** glTexImage3DEXT " << endl; }
extern "C" void fakeglTexBufferEXT(){ cerr << "*** glTexBufferEXT " << endl; }
extern "C" void fakeglClearColorIiEXT(){ cerr << "*** glClearColorIiEXT " << endl; }
extern "C" void fakeglClearColorIuiEXT(){ cerr << "*** glClearColorIuiEXT " << endl; }
extern "C" void fakeglGetTexParameterIivEXT(){ cerr << "*** glGetTexParameterIivEXT " << endl; }
extern "C" void fakeglGetTexParameterIuivEXT(){ cerr << "*** glGetTexParameterIuivEXT " << endl; }
extern "C" void fakeglTexParameterIivEXT(){ cerr << "*** glTexParameterIivEXT " << endl; }
extern "C" void fakeglTexParameterIuivEXT(){ cerr << "*** glTexParameterIuivEXT " << endl; }
extern "C" void fakeglAreTexturesResidentEXT(){ cerr << "*** glAreTexturesResidentEXT " << endl; }
extern "C" void fakeglBindTextureEXT(){ cerr << "*** glBindTextureEXT " << endl; }
extern "C" void fakeglDeleteTexturesEXT(){ cerr << "*** glDeleteTexturesEXT " << endl; }
extern "C" void fakeglGenTexturesEXT(){ cerr << "*** glGenTexturesEXT " << endl; }
extern "C" void fakeglIsTextureEXT(){ cerr << "*** glIsTextureEXT " << endl; }
extern "C" void fakeglPrioritizeTexturesEXT(){ cerr << "*** glPrioritizeTexturesEXT " << endl; }
extern "C" void fakeglGetQueryObjecti64vEXT(){ cerr << "*** glGetQueryObjecti64vEXT " << endl; }
extern "C" void fakeglGetQueryObjectui64vEXT(){ cerr << "*** glGetQueryObjectui64vEXT " << endl; }
extern "C" void fakeglArrayElementEXT(){ cerr << "*** glArrayElementEXT " << endl; }
extern "C" void fakeglColorPointerEXT(){ cerr << "*** glColorPointerEXT " << endl; }
extern "C" void fakeglDrawArraysEXT(){ cerr << "*** glDrawArraysEXT " << endl; }
extern "C" void fakeglEdgeFlagPointerEXT(){ cerr << "*** glEdgeFlagPointerEXT " << endl; }
extern "C" void fakeglGetPointervEXT(){ cerr << "*** glGetPointervEXT " << endl; }
extern "C" void fakeglIndexPointerEXT(){ cerr << "*** glIndexPointerEXT " << endl; }
extern "C" void fakeglNormalPointerEXT(){ cerr << "*** glNormalPointerEXT " << endl; }
extern "C" void fakeglTexCoordPointerEXT(){ cerr << "*** glTexCoordPointerEXT " << endl; }
extern "C" void fakeglVertexPointerEXT(){ cerr << "*** glVertexPointerEXT " << endl; }
extern "C" void fakeglBufferRegionEnabledEXT(){ cerr << "*** glBufferRegionEnabledEXT " << endl; }
extern "C" void fakeglDeleteBufferRegionEXT(){ cerr << "*** glDeleteBufferRegionEXT " << endl; }
extern "C" void fakeglDrawBufferRegionEXT(){ cerr << "*** glDrawBufferRegionEXT " << endl; }
extern "C" void fakeglNewBufferRegionEXT(){ cerr << "*** glNewBufferRegionEXT " << endl; }
extern "C" void fakeglReadBufferRegionEXT(){ cerr << "*** glReadBufferRegionEXT " << endl; }
extern "C" void fakeglClearDepthdNV(){ cerr << "*** glClearDepthdNV " << endl; }
extern "C" void fakeglDepthBoundsdNV(){ cerr << "*** glDepthBoundsdNV " << endl; }
extern "C" void fakeglDepthRangedNV(){ cerr << "*** glDepthRangedNV " << endl; }
extern "C" void fakeglDeleteFencesNV(){ cerr << "*** glDeleteFencesNV " << endl; }
extern "C" void fakeglFinishFenceNV(){ cerr << "*** glFinishFenceNV " << endl; }
extern "C" void fakeglGenFencesNV(){ cerr << "*** glGenFencesNV " << endl; }
extern "C" void fakeglGetFenceivNV(){ cerr << "*** glGetFenceivNV " << endl; }
extern "C" void fakeglIsFenceNV(){ cerr << "*** glIsFenceNV " << endl; }
extern "C" void fakeglSetFenceNV(){ cerr << "*** glSetFenceNV " << endl; }
extern "C" void fakeglTestFenceNV(){ cerr << "*** glTestFenceNV " << endl; }
extern "C" void fakeglGetProgramNamedParameterdvNV(){ cerr << "*** glGetProgramNamedParameterdvNV " << endl; }
extern "C" void fakeglGetProgramNamedParameterfvNV(){ cerr << "*** glGetProgramNamedParameterfvNV " << endl; }
extern "C" void fakeglProgramNamedParameter4dNV(){ cerr << "*** glProgramNamedParameter4dNV " << endl; }
extern "C" void fakeglProgramNamedParameter4dvNV(){ cerr << "*** glProgramNamedParameter4dvNV " << endl; }
extern "C" void fakeglProgramNamedParameter4fNV(){ cerr << "*** glProgramNamedParameter4fNV " << endl; }
extern "C" void fakeglProgramNamedParameter4fvNV(){ cerr << "*** glProgramNamedParameter4fvNV " << endl; }
extern "C" void fakeglRenderbufferStorageMultisampleCoverageNV(){ cerr << "*** glRenderbufferStorageMultisampleCoverageNV " << endl; }
extern "C" void fakeglProgramEnvParameterI4iNV(){ cerr << "*** glProgramEnvParameterI4iNV " << endl; }
extern "C" void fakeglProgramEnvParameterI4ivNV(){ cerr << "*** glProgramEnvParameterI4ivNV " << endl; }
extern "C" void fakeglProgramEnvParameterI4uiNV(){ cerr << "*** glProgramEnvParameterI4uiNV " << endl; }
extern "C" void fakeglProgramEnvParameterI4uivNV(){ cerr << "*** glProgramEnvParameterI4uivNV " << endl; }
extern "C" void fakeglProgramEnvParametersI4ivNV(){ cerr << "*** glProgramEnvParametersI4ivNV " << endl; }
extern "C" void fakeglProgramEnvParametersI4uivNV(){ cerr << "*** glProgramEnvParametersI4uivNV " << endl; }
extern "C" void fakeglProgramLocalParameterI4iNV(){ cerr << "*** glProgramLocalParameterI4iNV " << endl; }
extern "C" void fakeglProgramLocalParameterI4ivNV(){ cerr << "*** glProgramLocalParameterI4ivNV " << endl; }
extern "C" void fakeglProgramLocalParameterI4uiNV(){ cerr << "*** glProgramLocalParameterI4uiNV " << endl; }
extern "C" void fakeglProgramLocalParameterI4uivNV(){ cerr << "*** glProgramLocalParameterI4uivNV " << endl; }
extern "C" void fakeglProgramLocalParametersI4ivNV(){ cerr << "*** glProgramLocalParametersI4ivNV " << endl; }
extern "C" void fakeglProgramLocalParametersI4uivNV(){ cerr << "*** glProgramLocalParametersI4uivNV " << endl; }
extern "C" void fakeglColor3hNV(){ cerr << "*** glColor3hNV " << endl; }
extern "C" void fakeglColor3hvNV(){ cerr << "*** glColor3hvNV " << endl; }
extern "C" void fakeglColor4hNV(){ cerr << "*** glColor4hNV " << endl; }
extern "C" void fakeglColor4hvNV(){ cerr << "*** glColor4hvNV " << endl; }
extern "C" void fakeglFogCoordhNV(){ cerr << "*** glFogCoordhNV " << endl; }
extern "C" void fakeglFogCoordhvNV(){ cerr << "*** glFogCoordhvNV " << endl; }
extern "C" void fakeglMultiTexCoord1hNV(){ cerr << "*** glMultiTexCoord1hNV " << endl; }
extern "C" void fakeglMultiTexCoord1hvNV(){ cerr << "*** glMultiTexCoord1hvNV " << endl; }
extern "C" void fakeglMultiTexCoord2hNV(){ cerr << "*** glMultiTexCoord2hNV " << endl; }
extern "C" void fakeglMultiTexCoord2hvNV(){ cerr << "*** glMultiTexCoord2hvNV " << endl; }
extern "C" void fakeglMultiTexCoord3hNV(){ cerr << "*** glMultiTexCoord3hNV " << endl; }
extern "C" void fakeglMultiTexCoord3hvNV(){ cerr << "*** glMultiTexCoord3hvNV " << endl; }
extern "C" void fakeglMultiTexCoord4hNV(){ cerr << "*** glMultiTexCoord4hNV " << endl; }
extern "C" void fakeglMultiTexCoord4hvNV(){ cerr << "*** glMultiTexCoord4hvNV " << endl; }
extern "C" void fakeglNormal3hNV(){ cerr << "*** glNormal3hNV " << endl; }
extern "C" void fakeglNormal3hvNV(){ cerr << "*** glNormal3hvNV " << endl; }
extern "C" void fakeglSecondaryColor3hNV(){ cerr << "*** glSecondaryColor3hNV " << endl; }
extern "C" void fakeglSecondaryColor3hvNV(){ cerr << "*** glSecondaryColor3hvNV " << endl; }
extern "C" void fakeglTexCoord1hNV(){ cerr << "*** glTexCoord1hNV " << endl; }
extern "C" void fakeglTexCoord1hvNV(){ cerr << "*** glTexCoord1hvNV " << endl; }
extern "C" void fakeglTexCoord2hNV(){ cerr << "*** glTexCoord2hNV " << endl; }
extern "C" void fakeglTexCoord2hvNV(){ cerr << "*** glTexCoord2hvNV " << endl; }
extern "C" void fakeglTexCoord3hNV(){ cerr << "*** glTexCoord3hNV " << endl; }
extern "C" void fakeglTexCoord3hvNV(){ cerr << "*** glTexCoord3hvNV " << endl; }
extern "C" void fakeglTexCoord4hNV(){ cerr << "*** glTexCoord4hNV " << endl; }
extern "C" void fakeglTexCoord4hvNV(){ cerr << "*** glTexCoord4hvNV " << endl; }
extern "C" void fakeglVertex2hNV(){ cerr << "*** glVertex2hNV " << endl; }
extern "C" void fakeglVertex2hvNV(){ cerr << "*** glVertex2hvNV " << endl; }
extern "C" void fakeglVertex3hNV(){ cerr << "*** glVertex3hNV " << endl; }
extern "C" void fakeglVertex3hvNV(){ cerr << "*** glVertex3hvNV " << endl; }
extern "C" void fakeglVertex4hNV(){ cerr << "*** glVertex4hNV " << endl; }
extern "C" void fakeglVertex4hvNV(){ cerr << "*** glVertex4hvNV " << endl; }
extern "C" void fakeglVertexAttrib1hNV(){ cerr << "*** glVertexAttrib1hNV " << endl; }
extern "C" void fakeglVertexAttrib1hvNV(){ cerr << "*** glVertexAttrib1hvNV " << endl; }
extern "C" void fakeglVertexAttrib2hNV(){ cerr << "*** glVertexAttrib2hNV " << endl; }
extern "C" void fakeglVertexAttrib2hvNV(){ cerr << "*** glVertexAttrib2hvNV " << endl; }
extern "C" void fakeglVertexAttrib3hNV(){ cerr << "*** glVertexAttrib3hNV " << endl; }
extern "C" void fakeglVertexAttrib3hvNV(){ cerr << "*** glVertexAttrib3hvNV " << endl; }
extern "C" void fakeglVertexAttrib4hNV(){ cerr << "*** glVertexAttrib4hNV " << endl; }
extern "C" void fakeglVertexAttrib4hvNV(){ cerr << "*** glVertexAttrib4hvNV " << endl; }
extern "C" void fakeglVertexAttribs1hvNV(){ cerr << "*** glVertexAttribs1hvNV " << endl; }
extern "C" void fakeglVertexAttribs2hvNV(){ cerr << "*** glVertexAttribs2hvNV " << endl; }
extern "C" void fakeglVertexAttribs3hvNV(){ cerr << "*** glVertexAttribs3hvNV " << endl; }
extern "C" void fakeglVertexAttribs4hvNV(){ cerr << "*** glVertexAttribs4hvNV " << endl; }
extern "C" void fakeglVertexWeighthNV(){ cerr << "*** glVertexWeighthNV " << endl; }
extern "C" void fakeglVertexWeighthvNV(){ cerr << "*** glVertexWeighthvNV " << endl; }
extern "C" void fakeglBeginOcclusionQueryNV(){ cerr << "*** glBeginOcclusionQueryNV " << endl; }
extern "C" void fakeglDeleteOcclusionQueriesNV(){ cerr << "*** glDeleteOcclusionQueriesNV " << endl; }
extern "C" void fakeglEndOcclusionQueryNV(){ cerr << "*** glEndOcclusionQueryNV " << endl; }
extern "C" void fakeglGenOcclusionQueriesNV(){ cerr << "*** glGenOcclusionQueriesNV " << endl; }
extern "C" void fakeglGetOcclusionQueryivNV(){ cerr << "*** glGetOcclusionQueryivNV " << endl; }
extern "C" void fakeglGetOcclusionQueryuivNV(){ cerr << "*** glGetOcclusionQueryuivNV " << endl; }
extern "C" void fakeglIsOcclusionQueryNV(){ cerr << "*** glIsOcclusionQueryNV " << endl; }
extern "C" void fakeglProgramBufferParametersIivNV(){ cerr << "*** glProgramBufferParametersIivNV " << endl; }
extern "C" void fakeglProgramBufferParametersIuivNV(){ cerr << "*** glProgramBufferParametersIuivNV " << endl; }
extern "C" void fakeglProgramBufferParametersfvNV(){ cerr << "*** glProgramBufferParametersfvNV " << endl; }
extern "C" void fakeglFlushPixelDataRangeNV(){ cerr << "*** glFlushPixelDataRangeNV " << endl; }
extern "C" void fakeglPixelDataRangeNV(){ cerr << "*** glPixelDataRangeNV " << endl; }
extern "C" void fakeglPointParameteriNV(){ cerr << "*** glPointParameteriNV " << endl; }
extern "C" void fakeglPointParameterivNV(){ cerr << "*** glPointParameterivNV " << endl; }
extern "C" void fakeglPrimitiveRestartIndexNV(){ cerr << "*** glPrimitiveRestartIndexNV " << endl; }
extern "C" void fakeglPrimitiveRestartNV(){ cerr << "*** glPrimitiveRestartNV " << endl; }
extern "C" void fakeglCombinerInputNV(){ cerr << "*** glCombinerInputNV " << endl; }
extern "C" void fakeglCombinerOutputNV(){ cerr << "*** glCombinerOutputNV " << endl; }
extern "C" void fakeglCombinerParameterfNV(){ cerr << "*** glCombinerParameterfNV " << endl; }
extern "C" void fakeglCombinerParameterfvNV(){ cerr << "*** glCombinerParameterfvNV " << endl; }
extern "C" void fakeglCombinerParameteriNV(){ cerr << "*** glCombinerParameteriNV " << endl; }
extern "C" void fakeglCombinerParameterivNV(){ cerr << "*** glCombinerParameterivNV " << endl; }
extern "C" void fakeglFinalCombinerInputNV(){ cerr << "*** glFinalCombinerInputNV " << endl; }
extern "C" void fakeglGetCombinerInputParameterfvNV(){ cerr << "*** glGetCombinerInputParameterfvNV " << endl; }
extern "C" void fakeglGetCombinerInputParameterivNV(){ cerr << "*** glGetCombinerInputParameterivNV " << endl; }
extern "C" void fakeglGetCombinerOutputParameterfvNV(){ cerr << "*** glGetCombinerOutputParameterfvNV " << endl; }
extern "C" void fakeglGetCombinerOutputParameterivNV(){ cerr << "*** glGetCombinerOutputParameterivNV " << endl; }
extern "C" void fakeglGetFinalCombinerInputParameterfvNV(){ cerr << "*** glGetFinalCombinerInputParameterfvNV " << endl; }
extern "C" void fakeglGetFinalCombinerInputParameterivNV(){ cerr << "*** glGetFinalCombinerInputParameterivNV " << endl; }
extern "C" void fakeglCombinerStageParameterfvNV(){ cerr << "*** glCombinerStageParameterfvNV " << endl; }
extern "C" void fakeglGetCombinerStageParameterfvNV(){ cerr << "*** glGetCombinerStageParameterfvNV " << endl; }
extern "C" void fakeglActiveVaryingNV(){ cerr << "*** glActiveVaryingNV " << endl; }
extern "C" void fakeglBeginTransformFeedbackNV(){ cerr << "*** glBeginTransformFeedbackNV " << endl; }
extern "C" void fakeglBindBufferBaseNV(){ cerr << "*** glBindBufferBaseNV " << endl; }
extern "C" void fakeglBindBufferOffsetNV(){ cerr << "*** glBindBufferOffsetNV " << endl; }
extern "C" void fakeglBindBufferRangeNV(){ cerr << "*** glBindBufferRangeNV " << endl; }
extern "C" void fakeglEndTransformFeedbackNV(){ cerr << "*** glEndTransformFeedbackNV " << endl; }
extern "C" void fakeglGetActiveVaryingNV(){ cerr << "*** glGetActiveVaryingNV " << endl; }
extern "C" void fakeglGetTransformFeedbackVaryingNV(){ cerr << "*** glGetTransformFeedbackVaryingNV " << endl; }
extern "C" void fakeglGetVaryingLocationNV(){ cerr << "*** glGetVaryingLocationNV " << endl; }
extern "C" void fakeglTransformFeedbackAttribsNV(){ cerr << "*** glTransformFeedbackAttribsNV " << endl; }
extern "C" void fakeglTransformFeedbackVaryingsNV(){ cerr << "*** glTransformFeedbackVaryingsNV " << endl; }
extern "C" void fakeglFlushVertexArrayRangeNV(){ cerr << "*** glFlushVertexArrayRangeNV " << endl; }
extern "C" void fakeglVertexArrayRangeNV(){ cerr << "*** glVertexArrayRangeNV " << endl; }
extern "C" void fakeglAreProgramsResidentNV(){ cerr << "*** glAreProgramsResidentNV " << endl; }
extern "C" void fakeglBindProgramNV(){ cerr << "*** glBindProgramNV " << endl; }
extern "C" void fakeglDeleteProgramsNV(){ cerr << "*** glDeleteProgramsNV " << endl; }
extern "C" void fakeglExecuteProgramNV(){ cerr << "*** glExecuteProgramNV " << endl; }
extern "C" void fakeglGenProgramsNV(){ cerr << "*** glGenProgramsNV " << endl; }
extern "C" void fakeglGetProgramParameterdvNV(){ cerr << "*** glGetProgramParameterdvNV " << endl; }
extern "C" void fakeglGetProgramParameterfvNV(){ cerr << "*** glGetProgramParameterfvNV " << endl; }
extern "C" void fakeglGetProgramStringNV(){ cerr << "*** glGetProgramStringNV " << endl; }
extern "C" void fakeglGetProgramivNV(){ cerr << "*** glGetProgramivNV " << endl; }
extern "C" void fakeglGetTrackMatrixivNV(){ cerr << "*** glGetTrackMatrixivNV " << endl; }
extern "C" void fakeglGetVertexAttribPointervNV(){ cerr << "*** glGetVertexAttribPointervNV " << endl; }
extern "C" void fakeglGetVertexAttribdvNV(){ cerr << "*** glGetVertexAttribdvNV " << endl; }
extern "C" void fakeglGetVertexAttribfvNV(){ cerr << "*** glGetVertexAttribfvNV " << endl; }
extern "C" void fakeglGetVertexAttribivNV(){ cerr << "*** glGetVertexAttribivNV " << endl; }
extern "C" void fakeglIsProgramNV(){ cerr << "*** glIsProgramNV " << endl; }
extern "C" void fakeglLoadProgramNV(){ cerr << "*** glLoadProgramNV " << endl; }
extern "C" void fakeglProgramParameter4dNV(){ cerr << "*** glProgramParameter4dNV " << endl; }
extern "C" void fakeglProgramParameter4dvNV(){ cerr << "*** glProgramParameter4dvNV " << endl; }
extern "C" void fakeglProgramParameter4fNV(){ cerr << "*** glProgramParameter4fNV " << endl; }
extern "C" void fakeglProgramParameter4fvNV(){ cerr << "*** glProgramParameter4fvNV " << endl; }
extern "C" void fakeglProgramParameters4dvNV(){ cerr << "*** glProgramParameters4dvNV " << endl; }
extern "C" void fakeglProgramParameters4fvNV(){ cerr << "*** glProgramParameters4fvNV " << endl; }
extern "C" void fakeglRequestResidentProgramsNV(){ cerr << "*** glRequestResidentProgramsNV " << endl; }
extern "C" void fakeglTrackMatrixNV(){ cerr << "*** glTrackMatrixNV " << endl; }
extern "C" void fakeglVertexAttrib1dNV(){ cerr << "*** glVertexAttrib1dNV " << endl; }
extern "C" void fakeglVertexAttrib1dvNV(){ cerr << "*** glVertexAttrib1dvNV " << endl; }
extern "C" void fakeglVertexAttrib1fNV(){ cerr << "*** glVertexAttrib1fNV " << endl; }
extern "C" void fakeglVertexAttrib1fvNV(){ cerr << "*** glVertexAttrib1fvNV " << endl; }
extern "C" void fakeglVertexAttrib1sNV(){ cerr << "*** glVertexAttrib1sNV " << endl; }
extern "C" void fakeglVertexAttrib1svNV(){ cerr << "*** glVertexAttrib1svNV " << endl; }
extern "C" void fakeglVertexAttrib2dNV(){ cerr << "*** glVertexAttrib2dNV " << endl; }
extern "C" void fakeglVertexAttrib2dvNV(){ cerr << "*** glVertexAttrib2dvNV " << endl; }
extern "C" void fakeglVertexAttrib2fNV(){ cerr << "*** glVertexAttrib2fNV " << endl; }
extern "C" void fakeglVertexAttrib2fvNV(){ cerr << "*** glVertexAttrib2fvNV " << endl; }
extern "C" void fakeglVertexAttrib2sNV(){ cerr << "*** glVertexAttrib2sNV " << endl; }
extern "C" void fakeglVertexAttrib2svNV(){ cerr << "*** glVertexAttrib2svNV " << endl; }
extern "C" void fakeglVertexAttrib3dNV(){ cerr << "*** glVertexAttrib3dNV " << endl; }
extern "C" void fakeglVertexAttrib3dvNV(){ cerr << "*** glVertexAttrib3dvNV " << endl; }
extern "C" void fakeglVertexAttrib3fNV(){ cerr << "*** glVertexAttrib3fNV " << endl; }
extern "C" void fakeglVertexAttrib3fvNV(){ cerr << "*** glVertexAttrib3fvNV " << endl; }
extern "C" void fakeglVertexAttrib3sNV(){ cerr << "*** glVertexAttrib3sNV " << endl; }
extern "C" void fakeglVertexAttrib3svNV(){ cerr << "*** glVertexAttrib3svNV " << endl; }
extern "C" void fakeglVertexAttrib4dNV(){ cerr << "*** glVertexAttrib4dNV " << endl; }
extern "C" void fakeglVertexAttrib4dvNV(){ cerr << "*** glVertexAttrib4dvNV " << endl; }
extern "C" void fakeglVertexAttrib4fNV(){ cerr << "*** glVertexAttrib4fNV " << endl; }
extern "C" void fakeglVertexAttrib4fvNV(){ cerr << "*** glVertexAttrib4fvNV " << endl; }
extern "C" void fakeglVertexAttrib4sNV(){ cerr << "*** glVertexAttrib4sNV " << endl; }
extern "C" void fakeglVertexAttrib4svNV(){ cerr << "*** glVertexAttrib4svNV " << endl; }
extern "C" void fakeglVertexAttrib4ubNV(){ cerr << "*** glVertexAttrib4ubNV " << endl; }
extern "C" void fakeglVertexAttrib4ubvNV(){ cerr << "*** glVertexAttrib4ubvNV " << endl; }
extern "C" void fakeglVertexAttribPointerNV(){ cerr << "*** glVertexAttribPointerNV " << endl; }
extern "C" void fakeglVertexAttribs1dvNV(){ cerr << "*** glVertexAttribs1dvNV " << endl; }
extern "C" void fakeglVertexAttribs1fvNV(){ cerr << "*** glVertexAttribs1fvNV " << endl; }
extern "C" void fakeglVertexAttribs1svNV(){ cerr << "*** glVertexAttribs1svNV " << endl; }
extern "C" void fakeglVertexAttribs2dvNV(){ cerr << "*** glVertexAttribs2dvNV " << endl; }
extern "C" void fakeglVertexAttribs2fvNV(){ cerr << "*** glVertexAttribs2fvNV " << endl; }
extern "C" void fakeglVertexAttribs2svNV(){ cerr << "*** glVertexAttribs2svNV " << endl; }
extern "C" void fakeglVertexAttribs3dvNV(){ cerr << "*** glVertexAttribs3dvNV " << endl; }
extern "C" void fakeglVertexAttribs3fvNV(){ cerr << "*** glVertexAttribs3fvNV " << endl; }
extern "C" void fakeglVertexAttribs3svNV(){ cerr << "*** glVertexAttribs3svNV " << endl; }
extern "C" void fakeglVertexAttribs4dvNV(){ cerr << "*** glVertexAttribs4dvNV " << endl; }
extern "C" void fakeglVertexAttribs4fvNV(){ cerr << "*** glVertexAttribs4fvNV " << endl; }
extern "C" void fakeglVertexAttribs4svNV(){ cerr << "*** glVertexAttribs4svNV " << endl; }
extern "C" void fakeglVertexAttribs4ubvNV(){ cerr << "*** glVertexAttribs4ubvNV " << endl; }
extern "C" void fakeglXCreatePbuffer(){ cerr << "*** glXCreatePbuffer " << endl; }
extern "C" void fakeglXCreatePixmap(){ cerr << "*** glXCreatePixmap " << endl; }
extern "C" void fakeglXCreateWindow(){ cerr << "*** glXCreateWindow " << endl; }
extern "C" void fakeglXDestroyPbuffer(){ cerr << "*** glXDestroyPbuffer " << endl; }
extern "C" void fakeglXDestroyPixmap(){ cerr << "*** glXDestroyPixmap " << endl; }
extern "C" void fakeglXDestroyWindow(){ cerr << "*** glXDestroyWindow " << endl; }
extern "C" void fakeglXGetFBConfigAttrib(){ cerr << "*** glXGetFBConfigAttrib " << endl; }
extern "C" void fakeglXGetFBConfigs(){ cerr << "*** glXGetFBConfigs " << endl; }
extern "C" void fakeglXGetSelectedEvent(){ cerr << "*** glXGetSelectedEvent " << endl; }
extern "C" void fakeglXQueryContext(){ cerr << "*** glXQueryContext " << endl; }
extern "C" void fakeglXQueryDrawable(){ cerr << "*** glXQueryDrawable " << endl; }
extern "C" void fakeglXSelectEvent(){ cerr << "*** glXSelectEvent " << endl; }
extern "C" void fakeglXFreeContextEXT() { cerr << "*** glXFreeContextEXT" << endl; }
extern "C" void fakeglXGetContextIDEXT() { cerr << "*** glXGetContextIDEXT" << endl; }
extern "C" void fakeglXImportContextEXT() { cerr << "*** glXImportContextEXT" << endl; }
extern "C" void fakeglXQueryContextInfoEXT() { cerr << "*** glXQueryContextInfoEXT" << endl; }
extern "C" void fakeglXChooseFBConfigSGIX() { cerr << "*** glXChooseFBConfigSGIX" << endl; }
extern "C" void fakeglXCreateContextWithConfigSGIX() { cerr << "*** glXCreateContextWithConfigSGIX" << endl; }
extern "C" void fakeglXCreateGLXPixmapWithConfigSGIX() { cerr << "*** glXCreateGLXPixmapWithConfigSGIX" << endl; }
extern "C" void fakeglXGetFBConfigAttribSGIX() { cerr << "*** glXGetFBConfigAttribSGIX" << endl; }
extern "C" void fakeglXGetFBConfigFromVisualSGIX() { cerr << "*** glXGetFBConfigFromVisualSGIX" << endl; }
extern "C" void fakeglXGetVisualFromFBConfigSGIX() { cerr << "*** glXGetVisualFromFBConfigSGIX" << endl; }
extern "C" void fakeglXCreateGLXPbufferSGIX() { cerr << "*** glXCreateGLXPbufferSGIX" << endl; }
extern "C" void fakeglXDestroyGLXPbufferSGIX() { cerr << "*** glXDestroyGLXPbufferSGIX" << endl; }
extern "C" void fakeglXGetSelectedEventSGIX() { cerr << "*** glXGetSelectedEventSGIX" << endl; }
extern "C" void fakeglXQueryGLXPbufferSGIX() { cerr << "*** glXQueryGLXPbufferSGIX" << endl; }
extern "C" void fakeglXSelectEventSGIX() { cerr << "*** glXSelectEventSGIX" << endl; }
extern "C" void fakeglXSwapIntervalSGI() { cerr << "*** glXSwapIntervalSGI" << endl; }
extern "C" void fakeglXGetVideoSyncSGI() { cerr << "*** glXGetVideoSyncSGI" << endl; }
extern "C" void fakeglXWaitVideoSyncSGI() { cerr << "*** glXWaitVideoSyncSGI" << endl; }
extern "C" void fakeglcuR0d4nX() { cerr << "*** glcuR0d4nX" << endl; }
extern "C" void fakeglMapNamedBufferEXT() { cerr << "*** glMapNamedBufferEXT" << endl; }
extern "C" void fakeglUnmapNamedBufferEXT() { cerr << "*** glUnmapNamedBufferEXT" << endl; }
extern "C" void fakeglGetNamedBufferParameterivEXT() { cerr << "*** glGetNamedBufferParameterivEXT" << endl; }
extern "C" void fakeglIsTexture() { cerr << "*** glIsTexture" << endl; }
extern "C" void fakeglGenTextures() { cerr << "*** glGenTextures" << endl; }
extern "C" void fakeglDeleteTextures() { cerr << "*** glDeleteTextures" << endl; }
extern "C" void fakeglBindTexture() { cerr << "*** glBindTexture" << endl; }
extern "C" void fakeglTexParameteri() { cerr << "*** glTexParameteri" << endl; }
extern "C" void fakeglGetTexParameteriv() { cerr << "*** glGetTexParameteriv" << endl; }
extern "C" void fakeglGetTexLevelParameteriv() { cerr << "*** glGetTexLevelParameteriv" << endl; }
extern "C" void fakeglTexImage2D() { cerr << "*** glTexImage2D" << endl; }
extern "C" void fakeglGetTextureImageEXT() { cerr << "*** glGetTextureImageEXT" << endl; }
extern "C" void fakeglTextureSubImage2DEXT() { cerr << "*** glTextureSubImage2DEXT" << endl; }
extern "C" void fakeglTextureSubImage3DEXT() { cerr << "*** glTextureSubImage3DEXT" << endl; }
extern "C" void fakeglIsRenderbuffer() { cerr << "*** glIsRenderbuffer" << endl; }
extern "C" void fakeglBindRenderbuffer() { cerr << "*** glBindRenderbuffer" << endl; }
extern "C" void fakeglGetRenderbufferParameteriv() { cerr << "*** glGetRenderbufferParameteriv" << endl; }
extern "C" void fakeglBindFramebuffer() { cerr << "*** glBindFramebuffer" << endl; }
extern "C" void fakeglDeleteFramebuffers() { cerr << "*** glDeleteFramebuffers" << endl; }
extern "C" void fakeglGenFramebuffers() { cerr << "*** glGenFramebuffers" << endl; }
extern "C" void fakeglFramebufferRenderbuffer() { cerr << "*** glFramebufferRenderbuffer" << endl; }
extern "C" void fakeglFramebufferTexture2D() { cerr << "*** glFramebufferTexture2D" << endl; }
extern "C" void fakeglBlitFramebuffer() { cerr << "*** glBlitFramebuffer" << endl; }
extern "C" void fakeglGetError() { cerr << "*** glGetError" << endl; }
extern "C" void fakeglGetIntegerv() { cerr << "*** glGetIntegerv" << endl; }
extern "C" void fakeglReadPixels() { cerr << "*** glReadPixels" << endl; }
extern "C" void fakeglPushAttrib() { cerr << "*** glPushAttrib" << endl; }
extern "C" void fakeglPopAttrib() { cerr << "*** glPopAttrib" << endl; }
extern "C" void fakeglDisable() { cerr << "*** glDisable" << endl; }
extern "C" void fakeglReadBuffer() { cerr << "*** glReadBuffer" << endl; }
